name: ✨ Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - core-platform
        - data-engineering
        - data-governance
        - data-warehousing
        - genai-ml
        - launch-accelerator
        - workspace-setup
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - New project
        - Enhancement to existing project
        - New utility/tool
        - Documentation improvement
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: Describe the use case or business problem
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      placeholder: Describe your proposed solution
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low - Nice to have
        - Medium - Would improve client experience
        - High - Critical for client success
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this